include: https://gitlab/Sensirion/Python/ci-config-python/raw/master/gitlab-ci-template-v2.yml
stages:
  - prepare
  - build
  - deploy

check_rst_syntax:
  stage: prepare
  extends: .check_rst_syntax_v2

check_editorconfig:
  stage: prepare
  extends: .check_editorconfig_v2


py3p6_linux_build:
  stage: build
  extends: .py3p6_linux_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'

py3p8_linux_build:
  stage: build
  extends: .py3p8_linux_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'


py3p8_64bit_win_build:
  stage: build
  extends: .py3p8_64bit_win_docker_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'

build_docs:
  stage: build
  extends: .build_docs_v2
  script:
    - python setup.py install
    - pip install -r docs/requirements.txt
    - cd docs
    - make html
  after_script:
    - mv docs/_build/html/ public/  # everything in public/ will get published
  artifacts:
    paths: [public]
    expire_in: 1 week
    when: always

deploy_staging:
  extends: .deploy_staging_v2

deploy_stable:
  extends: .deploy_stable_v2
  environment:
    name: pypi.org
    url: https://pypi.org/project/sensirion_i2c_sfm_sf06/
  before_script:
    - pip install twine~=1.12.1
  script:
    - PKG_VERSION=$(python setup.py --version --quiet | tail -n1)
    - TAG_VERSION=$(git describe --tags)
    - if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then echo "Tag Version ($TAG_VERSION) != Package Version ($PKG_VERSION)" && exit 1; fi
    - twine upload dist/*

deploy_docs:
  stage: deploy
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.8-20.04-2.6.0
  dependencies: []
  only: [master, tags]
  script:
    - python setup.py install
    - pip install -r docs/requirements.txt
    - cd docs
    - make html
  after_script:
    - chmod 777 ./ci/set_git_config.sh
    - ./ci/set_git_config.sh
    - chmod 777 ./ci/checkin_doc.sh
    - ./ci/checkin_doc.sh

TODO_check:
  stage: prepare
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.2.0
  tags: [linux, docker]
  script:
    - '! grep -rnw --exclude=.gitlab-ci.yml --exclude-dir=.git . -e "TODO"'